# Generated by Django 5.0.6 on 2024-09-01 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descriptiom',
            new_name='description',
        ),
    ]
