# Generated by Django 5.0.6 on 2024-09-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_thumbail_project_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersummary',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
