# Generated by Django 5.0.6 on 2024-09-18 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='commant',
            new_name='comment',
        ),
    ]
